/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Encapsulamento_EX04;

import javax.swing.JOptionPane;

/**
 *
 * @author leele
 */
public class NumerosVIEW extends javax.swing.JFrame {

    /**
     * Creates new form NumerosVIEW
     */
    public NumerosVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNome = new javax.swing.JLabel();
        LabelN2 = new javax.swing.JLabel();
        LabelN1 = new javax.swing.JLabel();
        LabelN3 = new javax.swing.JLabel();
        LabelN4 = new javax.swing.JLabel();
        N2Field = new javax.swing.JTextField();
        N1Field = new javax.swing.JTextField();
        N4Field = new javax.swing.JTextField();
        N3Field = new javax.swing.JTextField();
        OrdernarBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNome.setText("Ordernar Números");

        LabelN2.setText("Número 2: ");

        LabelN1.setText("Número 1: ");

        LabelN3.setText("Número 3: ");

        LabelN4.setText("Número 4: ");

        N1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N1FieldActionPerformed(evt);
            }
        });

        OrdernarBotao.setText("Ordenar");
        OrdernarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdernarBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(OrdernarBotao)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelN3)
                            .addGap(18, 18, 18)
                            .addComponent(N3Field))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelN2)
                            .addGap(18, 18, 18)
                            .addComponent(N2Field))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelN1)
                            .addGap(18, 18, 18)
                            .addComponent(N1Field))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelN4)
                            .addGap(18, 18, 18)
                            .addComponent(N4Field, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(LabelNome)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelN1)
                    .addComponent(N1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(N2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelN2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelN3)
                    .addComponent(N3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelN4)
                    .addComponent(N4Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(OrdernarBotao)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OrdernarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdernarBotaoActionPerformed
        NumerosDTO numerosDTO = new NumerosDTO();
        NumerosCTR numerosCTR = new NumerosCTR();
        
        numerosDTO.setN1(Integer.parseInt(N1Field.getText()));
        numerosDTO.setN2(Integer.parseInt(N2Field.getText()));
        numerosDTO.setN3(Integer.parseInt(N3Field.getText()));
        numerosDTO.setN4(Integer.parseInt(N4Field.getText()));
        
        numerosCTR.ordernarNumeros(numerosDTO);
        JOptionPane.showMessageDialog(null, numerosCTR.Mostrar(numerosDTO));
    }//GEN-LAST:event_OrdernarBotaoActionPerformed

    private void N1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_N1FieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumerosVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumerosVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumerosVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumerosVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumerosVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelN1;
    private javax.swing.JLabel LabelN2;
    private javax.swing.JLabel LabelN3;
    private javax.swing.JLabel LabelN4;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JTextField N1Field;
    private javax.swing.JTextField N2Field;
    private javax.swing.JTextField N3Field;
    private javax.swing.JTextField N4Field;
    private javax.swing.JButton OrdernarBotao;
    // End of variables declaration//GEN-END:variables
}
